# Generated by Django 4.0.5 on 2022-07-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(1, 'Repetitions'), (2, 'Seconds')], default=1)),
                ('series', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_series', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.workoutactivity')),
            ],
        ),
    ]
