# Generated by Django 4.0.5 on 2022-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_dailytraining_user_alter_waterincome_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytraining',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
