# Generated by Django 4.0.5 on 2022-07-14 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0004_dailytraining_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 14)),
        ),
        migrations.AlterField(
            model_name='waterincome',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 14)),
        ),
        migrations.CreateModel(
            name='LongTermTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('value', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
