# Generated by Django 4.0.5 on 2022-07-14 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_dailytraining_date_alter_waterincome_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytraining',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 12, 33, 30, 566657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='waterincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 12, 33, 30, 566920, tzinfo=utc)),
        ),
    ]
