# Generated by Django 4.0.5 on 2022-07-21 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0006_alter_dailytraining_date_alter_waterincome_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volumes', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 13, 15, 29, 223370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='waterincome',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 21, 13, 15, 29, 223638, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2022, 7, 21, 13, 15, 29, 224443, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='todo_list.consumptioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
