# Generated by Django 4.0.5 on 2022-07-21 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0007_consumptioncategory_alter_dailytraining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumption',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailytraining',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waterincome',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
