# Generated by Django 4.0.5 on 2022-07-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_dailyconsumption_date_alter_dailytraining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptioncategory',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
